# Piper Lovegreen
### Physical Geography Student at University of California, Santa Barbara
#### piper.lovegreen@gmail.com   
#### (805)729-8351
#

## <span style="color:darkgreen">Skills</span>
- Motivated
- Fast Learner
- Positive mindset 
- Thrives in Group Settings 

#
## <span style="color:darkgreen">Education</span>
### Associates in Arts Degree in Entrepreneurship at Santa Barbara City College
August 2014-May 2017

### Associates in Arts Degree in Geography at Santa Barbara City College 
 August 2017-May 2020
 
### <span style="color:seagreen">IN PROGRESS</span> Bachelor of Science in Physical Geography at University of California, Santa Barbara
September 2020-June 2022
#

## <span style="color:darkgreen">Employment History</span>
### Santa Barbara City College Tutoring 
#### Physical Geogrpahy Lab 
Fall 2019 and Spring 2020

####  Calculus II (Math 160)
Spring 2020

### University of California, Santa Barbara - Earth Research Institute 
6/14/17-8/9/17

#### - Assisted with contract and grant documentation/filing
#### - Organized research material 
#### - Cleaned offices/reseach space


### Piper Swimwear 
4/22/2015-7/5/2020

#### - Designed Swimwear 
#### - Managed financials 
#### - Developed and maintained website and social media
#### - Managed inventory and internet sales 

